language: c
compiler: gcc
install: sudo apt-get install biblatex texlive texlive-latex-extra texlive-bibtex-extra
  texlive-xetex texlive-math-extra texlive-latex3
script: cd book && ./build && cd ..
after_success: scripts/deploy.sh
notifications:
  irc: 
    channels:
      - "chat.freenode.net#learnmath"
    template:
      - "[\x0313%{repository_name}\x03] Build #%{build_number}: %{message} %{build_url}"
      - "\x0313%{repository_name}\x03/\x036%{branch}\x03 \x0314%{commit}\x03 \x0315%{author}\x03: %{commit_message}"
  on_success: change
  on_failure: change
